name: build-push

on:
  push:
    branches: [ main ]  # 只有 main 分支触发正式 build 和上线

env:
  IMAGE_NAME: ghcr.io/bbk66669/core

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set GIT_SHA
        run: echo "GIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_GH_PAT }}

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy-prod:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy main on remote
        uses: appleboy/ssh-action@v1
        with:
          host: 202.182.107.90
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/kk
            git fetch origin main
            git reset --hard origin/main
            echo "${{ secrets.CI_GH_PAT }}" | docker login ghcr.io -u bbk66669 --password-stdin
            docker compose -f docker-compose.yml pull core
            docker compose -f docker-compose.yml up -d --force-recreate core