name: deploy-gray
on:
  push:
    branches: [ gray ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare override config
        run: |
          rm -rf configs/config.override.yaml
          cp configs/gray.yaml configs/config.override.yaml

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      - name: Deploy Gray on Remote
        shell: bash
        env:
          GHCR_PAT:         ${{ secrets.CI_GH_PAT }}
          OKX_API_KEY:      ${{ secrets.OKX_API_KEY }}
          OKX_API_SECRET:   ${{ secrets.OKX_API_SECRET }}
          OKX_API_PASSPHRASE: ${{ secrets.OKX_API_PASSPHRASE }}
          OKX_API_FLAG:     ${{ secrets.OKX_API_FLAG }}
        run: |
          ssh -o StrictHostKeyChecking=yes root@202.182.107.90 << 'EOS'
            set -eo pipefail

            cd /root/kk
            git fetch origin gray
            git reset --hard origin/gray

            # Generate .env via echo (no HEREDOC)
            rm -f .env
            echo "OKX_API_KEY=${OKX_API_KEY}"     >> .env
            echo "OKX_API_SECRET=${OKX_API_SECRET}" >> .env
            echo "OKX_API_PASSPHRASE=${OKX_API_PASSPHRASE}" >> .env
            echo "OKX_API_FLAG=${OKX_API_FLAG}"    >> .env
            echo "WEAVIATE_URL=http://weaviate:8080"      >> .env
            echo "MEILISEARCH_URL=http://meilisearch:7700" >> .env
            echo "REDIS_URL=redis://redis:6379/0"         >> .env
            echo "USE_LOCAL_LLM=false"                   >> .env

            # Login & deploy
            echo "$GHCR_PAT" | docker login ghcr.io -u bbk66669 --password-stdin
            docker compose -f docker-compose.gray.yml pull core
            docker compose -f docker-compose.gray.yml up -d --force-recreate core
          EOS
