name: deploy-gray

on:
  push:
    branches: [ gray ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 写入 override + .env
      - name: prepare override config
        run: |
          cp configs/gray.yaml configs/config.override.yaml
          echo OKX_API_KEY=${{ secrets.OKX_API_KEY }}           >> .env
          echo OKX_API_SECRET=${{ secrets.OKX_API_SECRET }}     >> .env
          echo OKX_API_PASSPHRASE=${{ secrets.OKX_API_PASSPHRASE }} >> .env
          echo OKX_API_FLAG=${{ secrets.OKX_API_FLAG }}         >> .env

      # 加载 SSH 私钥
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote to known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts

      # 通过 SSH 在远端东京服务器上做灰度部署
      - name: Deploy Gray on Remote
        run: |
          ssh root@202.182.107.90 '
            cd /path/to/your/project &&
            docker compose -f docker-compose.gray.yml pull &&
            docker compose -f docker-compose.gray.yml up -d --force-recreate
          '
